### ISSUE TITLE
Well, it's great but... Well, it's great but...

### ISSUE THREAD

**Issue by jerguslejko** [matuskropuch/sort-it-out#4]
Hey mate! Great job! 👍 

Although, it seems that you tend to repeat yourself a lot. And you're not extracting logic (using functions/classes). For example:

```php
foreach ($boys as $boy) {
    $boys_names[] = $boy['name'];
}

foreach ($girls as $girl) {
    $girls_names[] = $girl['name'];
}
```

This could be easily extracted to something like this:

```php
function listNames($people) {
    $names = [];

    foreach($people as $person) {
        $names[] = $person['name'];
    }

    return $names;
}
```

also, the last line could be:

```
return implode(', ', $names);
```

Lots of options there. 🌵

**Comment by matuskropuch** [comment]
That's a great idea @jerguslejko thank you very much!

resolved in 8c9103d18c3a29e8d841a22d99867f477c6f3480
