### ISSUE TITLE
Hide the logic, hide the trouble

### ISSUE THREAD

**Issue by jerguslejko** [matuskropuch/sort-it-out#6]
Hey man,

you managed to refactor almost every loop, but, there is one left.

```php
foreach ($data as $person) {
    if ($person['gender'] == 'male') {
        $boys[] = $person;
    } else {
        $girls[] = $person;
    }
```

I think that something like this `$boys = getGender('male');` would be ways more readable...

**Comment by matuskropuch** [comment]
resolved in 08ac496f1e0915b4695e6e4d3d00343b965a80cd
